site_name: Doc Orléans
theme:
  name: material
  custom_dir: overrides

nav :
  - Home : index.md
  
  - Configuration :
    - -Plan d'adressage :  plan_adressage.md
    - Schéma ⤵️: 
      - -Infrastructure : schema.md
      - -Attribution des Ports : ports.md
    - -Switch :  switch.md
    - -PFsense : pfsense.md
    - -Serveur : serveur.md
    - Routeur ⤵️:  
      - Configuration : routeurs.md
      - NAT : NAT.md
      
    - -Serveur http(s) :  http_serv.md
    - -Stormshield :  Stormshield.md
    - -Resolveur :  resolveur_dns.md
    - -Reverse Proxy :  reverse_proxy.md
    - -Serveur DNS :  serveur_dns.md
    - -Serveur Docker: serveur_docker.md
    - -Serveur VPN: VPN_WireGuard.md
    - -Serveur Hmail: Hmail.md
    - -Guacamole : Guac.md
