site_name: Doc Orléans
theme:
  name: material
  custom_dir: overrides

nav :
  - Home : Document/index.md
  - Configuration :
    - -Plan d'adressage :  Document/plan_adressage.md
    - -Schéma :  Document/schema.md
    - -Switch :  Document/switch.md
    - -PFsense :  Document/pfsense.md
    - -Serveur :  Document/serveur.md
    - -Routeur :  Document/routeurs.md
    - -Serveur http(s) :  Document/http_serv.md
    - -Stormshield :  Document/Stormshield.md
    - -resolveur :  Document/resolveur_dns.md
    - -Reverse Proxy :  Document/reverse_proxy.md
    
