site_name: Doc Orléans
theme:
  name: material
  custom_dir: overrides

nav :
  - Home : index.md
  - Configuration :
    - -Schéma : schema.md
    - -Switch : switch.md
    - -ACL : acl.md
    - -Serveur : serveur.md
