site_name: Doc Orléans
theme:
  name: material
  custom_dir: overrides

nav :
  - Home : index.md
  - Configuration :
    - -Plan d'adressage :  plan_adressage.md
    - -Schéma :  schema.md
    - -Switch :  switch.md
    - -PFsense : pfsense.md
    - -Serveur : serveur.md
    - -Routeur :  routeurs.md
    - -Serveur http(s) :  http_serv.md
    - -Stormshield :  Stormshield.md
    - -resolveur :  resolveur_dns.md
    - -Reverse Proxy :  reverse_proxy.md
    
