site_name: Doc Orléans
theme:
  name: material
  custom_dir: overrides

nav :
  - Home : ../../Document/index.md
  - Configuration :
    - -Plan d'adressage :  /docs/Document/plan_adressage.md
    - -Schéma :  /docs/Document/schema.md
    - -Switch :  /docs/Document/switch.md
    - -PFsense :  /docs/Document/pfsense.md
    - -Serveur :  /docs/Document/serveur.md
    - -Routeur :  /docs/Document/routeurs.md
    - -Serveur http(s) :  /docs/Document/http_serv.md
    - -Stormshield :  /docs/Document/Stormshield.md
    - -resolveur :  /docs/Document/resolveur_dns.md
    - -Reverse Proxy :  /docs/Document/reverse_proxy.md
    
