site_name: Doc Orléans
theme:
  name: material
  custom_dir: overrides

nav :
  - Home : index.md
  - Nigeria : 
   - gg : niqe.md
  - Configuration :
    - -Plan d'adressage : plan_d'adressage.md
    - -Schéma : schema.md
    - -Switch : switch.md
    - -Serveur : serveur.md
    - -Routeur : routeurs.md
   
